### ISSUE TITLE
WFS is sometimes crashing input on IOS 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/mobile#1959] opened 2022-02-21 13:51 UTC
IOS 15.1
Input: 1.2.0 also 1.3.0
1. download project input-testing/tc06_format_wfs 
2. open the project 
3. input crash 

https://user-images.githubusercontent.com/94351263/154967865-2d89a9b6-6874-4f42-b0ea-fbb7d6daacb4.MP4

**Comment by tomasMizera** [comment] 2022-02-22 09:01
@PeterPetrik 

It does not always crash on my device, but it always generates 

Log:

```
Loading  "/var/mobile/Containers/Data/Application/2ED52375-C0A5-41EA-AAD5-B3307E11B0A7/Documents/INPUT/projects/tc06_format_wfs/test_format_wfs.qgz" false
program received signal 12, thread:2d5f86;00:4e00000000000000;01:0000000000000000;02:8007000000000000;03:c085f23601000000;04:f001000000000000;05:c085f23601000000;06:a900000000000000;07:43f99d8b00000000;08:0301000000000000;09:0301000000000000;0a:b0f00d0000000000;0b:419f170000000000;0c:7424000000000000;0d:4502000000000000;0e:0010100000000000;0f:8a00000000000000;10:ff00000000000000;11:80bf0f0000000000;12:0000000000000000;13:1020218202000000;14:0000000000000000;15:1820218202000000;16:08e4f38102000000;17:f841b66b01000000;18:e842b66b01000000;19:0000000000000000;1a:90789b0901000000;1b:98704d3401000000;1c:0000000000000000;1d:603fb66b01000000;1e:e4e6190801000000;1f:203fb66b01000000;20:b03df6c601000000;21:00000020;metype:5;mecount:2;medata:10003;medata:c;memory:0x16bb63f60=a03fb66b01000000246e190801000000;memory:0x16bb63fa0=f03fb66b01000000fc5f190801000000;
"2022-02-22T08:59:17.928Z InputPROJ: custom missing grid used by context handler OSTN15_NTv2_OSGBtoETRS.gsb\n"
"2022-02-22T08:59:17.969Z InputPROJ: missing preffered grid: OSTN15_NTv2_OSGBtoETRS.gsb\n"
stale focus object Page_QMLTYPE_43_QML_268(0x28197e680) , doing manual update
Warning 6: driver SQLite does not support creation option SPATIALITE
ERROR 6: OGR was built without libspatialite support
... sorry, creating/writing any SpatiaLite DB is unsupported

"2022-02-22T08:59:18.543Z QGIS WFS: Warning: Cannot create temporary SpatiaLite cache.: GDALCreate() failed: OGR was built without libspatialite support\n... sorry, creating/writing any SpatiaLite DB is unsupported\n\n"
```

**Comment by tomasMizera** [comment] 2022-02-22 09:02
I tested it within `cog` branch

**Comment by PeterPetrik** [comment] 2022-02-22 14:43
possible fix https://github.com/lutraconsulting/input-sdk/pull/66/commits/2f72626496a6d7311a49c36612549e510abf5837

**Comment by tomasMizera** [comment] 2022-03-10 15:20
How to make it crash with `cog` branch (https://github.com/lutraconsulting/input/pull/1957):
 - download and open the project (it does not crash on my device, but generates the mentioned error)
 - close app
 - run app
 - now it crashes (when the project should be opened as default one)

Also from that point on, I am not able to open the project. I can open other projects though.

**Comment by KlausAgerskov** [comment] 2022-08-25 10:37
I use WFS layers in a project and it crash every time I open the project on my IPhone 13

**Comment by tomasMizera** [comment] 2024-08-06 09:53
@VitorVieiraZ This is probably a duplicate of what you are exploring right now (#2493 )

**Comment by VitorVieiraZ** [comment] 2024-08-07 00:39
This issue can no longer be reproduced. However, the relationship between WFS layers and iOS still needs further review.

**Closed by VitorVieiraZ** 2024-08-07 00:39 UTC
Labels: bug, iOS, data corruption - sync failure - crash - anr
