### ISSUE TITLE
Alias expression not applied within Input

### ISSUE THREAD

**Issue by Tadeo98** [MerginMaps/mobile#2735] opened 2023-07-24 06:41 UTC
When having an alias expression set in QGIS for any field, in QGIS's form, this exact expression is present.
![image](https://github.com/MerginMaps/input/assets/94292549/5f9fe8de-8131-49b4-bf5c-15c115bc6e21)
![image](https://github.com/MerginMaps/input/assets/94292549/fff07a2f-92fe-4e96-8ce8-260546126abd)

But in Input, rather the original field name is used in the form.
![image](https://github.com/MerginMaps/input/assets/94292549/4a13d48c-8ad0-4284-8d7f-f87b952dac80)

**Comment by tomasMizera** [comment] 2023-11-13 12:43
This is more like enhancement

**Comment by tomasMizera** [comment] 2024-10-07 12:30
Duplicate of #3494

**Closed by tomasMizera** 2024-10-07 12:30 UTC
Labels: enhancement, forms
