### ISSUE TITLE
Value relation widget with multiple selections and not null constraint

### ISSUE THREAD

**Issue by erpas** [MerginMaps/mobile#3427] opened 2024-05-14 06:40 UTC
When a value relation widget with `Allow multiple selections` has also not null constraint, it would not allow to save values.
Users need to enter the widget once again, UNCHECK selected values and select some to satisfy the not null constraint.

**Comment by tomasMizera** [comment] 2024-05-14 09:22
Duplicate of #3418

**Closed by tomasMizera** 2024-05-14 09:22 UTC
Labels: bug
