### ISSUE TITLE
Symbol size is bigger than it should

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3223] opened 2024-04-03 10:22 UTC
In project tc03_map_canvas, there is a `SateliteAllLayers` map theme. Go to it and zoom in on the project. Then zoom in a little bit more so you can see one green line and a purple circle. The line has a set 1cm size and the circle has 2cm. On the online measurement tool https://onlineruler.org/, it looks like the circle is 2.5cm in size on the iPhone 11 and the line 1.25cm. 

Here is the regression test case for this: https://app.qase.io/case/INPUT-175

I am not sure how big this problem is.

**Comment by jozef-budac** [comment] 2024-04-04 06:51
@PatrikMizera can you check it?

**Comment by wonder-sk** [comment] 2024-04-05 10:50
@PatrikMizera please check the sizes:
- in the old app and the new app
- both ios and Android

(to make sure whether it is a regression or not)

**Comment by PatrikMizera** [comment] 2024-04-08 09:00
Android old version: 
- circle is 2,5 cm 
- line is 1,25 cm 

Android new (testing) version: 
- circle is 2,35 cm 
- line is 1,15 cm

**Comment by wonder-sk** [comment] 2024-04-11 10:03
@jozef-budac did you check that https://onlineruler.org/ has correct measurements? For me, it detected my 14" screen as 18.4" and the measurements were off (compared to my physical measurement tool).

In my testing:

| | Point 2cm | Line 1cm | Notes |
|--|--|--|--|
| QGIS (linux) | 1.55cm | 0.75cm | looks like a bug in QGIS |
| MM (linux) | 2.0cm | 1.0cm | :tada: |
| MM (android) | 2.0cm | 1.0cm | :tada: (Samsung Galaxy S21) |

I think even if the size is a bit off (like what Patrik has measured), it is fine, as long as it is not deviating more than e.g. 25%

@tomasMizera could you please try to measure the sizes on iOS? we can close the ticket if it roughly matches for you on iOS...

**Comment by tomasMizera** [comment] 2024-04-12 08:14
@wonder-sk I checked the iOS, here are the results:
 - Point is 2,1 cm
 - Line is 1,05 cm

Looks good to me to close the issue. 
Note: I checked the values with a physical ruler

**Closed by tomasMizera** 2024-04-12 08:14 UTC
Labels: iOS, bug in not released version

**Comment by jozef-budac** [comment] 2024-04-12 08:16
@wonder-sk  no I didn't check that https://onlineruler.org/ has the correct measurement.  I blindly believed this tool. Next time I will borrow meter from my kids :)

**Comment by PatrikMizera** [comment] 2024-04-12 08:21
RE-TESTED Android on the production version and also the 2024.1.0 version with a real physical ruler 📏and the measurements were correct with 2cm for the circle and 1cm for the line for both versions.
