### ISSUE TITLE
Google input suggestions gone

### ISSUE THREAD

**Issue by freeriderz** [MerginMaps/mobile#3486] opened 2024-06-02 17:44 UTC
Hello! So after recent app update the Google text input suggestions bar is gone when filling out text fields when adding a feature. I'm using the same project with custom made input form, and untill update the suggestions bar was there just above the keyboard, and was very helpful, but now, after app update it's gone. In other apps in the same table the bar is present as soon as I start typing, so for some reason the Mergin app is not allowing it to work/open/pop up. A fix would be nice. Thanks in advance!

**Comment by tomasMizera** [comment] 2024-06-03 14:45
Hi @freeriderz! Thanks for this report. This issue is already addressed and will be released soon (this week) as a part of 2024.2.0 version.

**Comment by tomasMizera** [comment] 2024-06-03 14:45
Duplicate of https://github.com/MerginMaps/mobile/issues/3434

**Closed by tomasMizera** 2024-06-03 14:45 UTC
