### ISSUE TITLE
Not possible to sync if user has Read-only access with local changes

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#3392] opened 2024-04-27 08:30 UTC
I have a survey team and I gave some Read-only access to the project. They make changes to the project and then they try to pull the changes from upstream.

Currently the app tries to do both:
- Upload changes from the read-only user
- Apply the upstream changes

This results in failure to sync and hence not possible to apply upstream changes to the Read-only users. The work-around is to delete and redownload the project. For a large project and limited bandwidth, this is not really feasible with 10s of users.

It would be good for the app to prompt the users, you don't have permission to upload your change and your local changes will be overwritten after the sync.

**Comment by tomasMizera** [comment] 2024-04-29 06:43
Duplicate of https://github.com/MerginMaps/mobile/issues/3174

**Closed by tomasMizera** 2024-04-29 06:43 UTC
