### ISSUE TITLE
Input stucks after granting camera permission

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#2877] opened 2023-10-25 10:16 UTC
In input 2.3.1 and later, the app freezes after granting camera permission for the first time. It happens on Android 13 devices. It may have something to do with the latest updates on Android, as it didn't happen before.

Scenario:
1) have a clear installation of input
2) create a simple project using Wizard with a photo 
3) open the project and hit the record button
4) try to record a picture, permission dialog will appear. 
5) try to grant the permission -> the app freezes.

https://github.com/MerginMaps/input/assets/83582181/b1ed82d8-5331-450b-b431-9f0918989e19

**Comment by tomasMizera** [comment] 2023-10-27 09:43
@jozef-budac Can you reproduce this on the latest version? I have Samsung with Android 13 and it works for me :/

**Comment by jozefbudac** [comment] 2023-10-27 19:55
I tried it on current production (2.4.0) and the app didn't freeze. I don't understand it, as I first noticed it on some APK with a fix (almost the latest master). But we can probably close it if we do not see more crashes from the Google Play console

**Comment by tomasMizera** [comment] 2023-11-13 12:07
Let's reopen if we can reproduce it

**Closed by tomasMizera** 2023-11-13 12:07 UTC
Labels: bug, android 🤖, high priority, not-reproducible
